CREATE DATABASE tt;

USE tt;

CREATE TABLE USER(
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	userId VARCHAR(50) NOT NULL,
	pwd VARCHAR(350) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	email VARCHAR(100) NOT NULL,
	tel VARCHAR(20),
	addr1 VARCHAR(300),
	addr2 VARCHAR(300) NOT NULL,
	regdate TIMESTAMP DEFAULT CURRENT_TIME()
);

CREATE TABLE role(
	id INT AUTO_INCREMENT PRIMARY KEY,
	roleName VARCHAR(20)
);

CREATE TABLE userRole(
	userId BIGINT,
	roleId INT
);

DESC ROLE;

DESC USER;

DESC user_role;

CREATE TABLE notice(
	nno INT PRIMARY KEY AUTO_INCREMENT,
	title varchar	
);

CREATE TABLE board(
	bno INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	author VARCHAR(20),
	regdate TIMESTAMP DEFAULT CURRENT_TIME,
	visited INT DEFAULT 0
);

INSERT INTO board VALUES (DEFAULT, '자유게시판 제목1', '자유게시판 내용1 입니다', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목2', '자유게시판 내용2 입니다', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목3', '자유게시판 내용3 입니다', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목4', '자유게시판 내용4 입니다', DEFAULT, DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목5', '자유게시판 내용5 입니다', DEFAULT, DEFAULT, DEFAULT);

CREATE TABLE product(
	pno INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
	content VARCHAR(2000) NOT NULL,
	price VARCHAR(200),
	location INT,
	regdate TIMESTAMP DEFAULT CURRENT_TIME,
	visited INT DEFAULT 0,
	status df 
);

CREATE TABLE productFile(
	pfno INT PRIMARY KEY AUTO_INCREMENT,
	
);

COMMIT;