CREATE DATABASE tt;

USE tt;

CREATE TABLE role(
	role_id INT PRIMARY KEY AUTO_INCREMENT,
	role VARCHAR(255) DEFAULT NULL
);

CREATE TABLE USER(
	user_id INT PRIMARY KEY AUTO_INCREMENT,
	active INT DEFAULT 0, 
	login_id VARCHAR(255) NOT NULL,
	user_name VARCHAR(255) NOT NULL,
	password VARCHAR(300) NOT NULL
);

CREATE TABLE user_role(
	user_id INT NOT NULL,
	role_id INT NOT NULL,
	PRIMARY KEY (user_id, role_id)
);

DESC ROLE;

DESC USER;

DESC user_role;

CREATE TABLE board(
	bno INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
	content VARCHAR(200) NOT NULL,
	regdate TIMESTAMP DEFAULT CURRENT_TIME,
	visited INT DEFAULT 0
);

INSERT INTO board VALUES (DEFAULT, '자유게시판 제목1', '자유게시판 내용1 입니다', DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목2', '자유게시판 내용2 입니다', DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목3', '자유게시판 내용3 입니다', DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목4', '자유게시판 내용4 입니다', DEFAULT, DEFAULT);
INSERT INTO board VALUES (DEFAULT, '자유게시판 제목5', '자유게시판 내용5 입니다', DEFAULT, DEFAULT);

COMMIT;